name: droid_synth_2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  msfa_plugin:
    path: ../msfa_plugin
  flutter_virtual_piano: ^0.0.6
  flutter_midi_command: ^0.4.8
  bonsai: ^1.0.1
  ninja_hex: ^2.0.1
  collection: ^1.17.0

dependency_overrides:
  flutter_midi_command_linux:
    git:
      url: https://github.com/maks/flutter_midi_command_linux/
      ref: update-package-deps

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
